name: GensouJank
main: net.gensokyoreimagined.gensoujank.GensouJank
version: 1.0-SNAPSHOT
api-version: 1.20
load: STARTUP
commands:
  touhouhitbox:
    usage: /<command> <player> <true/false>
    description: Toggles TouhouHitbox for a player
    permission: gensoujank.touhouhitbox
